name: bench GHA against GitLab
on:
  pull_request:

jobs:
  bench_gh:
    runs-on:                       self-hosted
    env:
      CARGO_INCREMENTAL:           0
      RUSTUP_HOME:                 /usr/local/rustup
      CARGO_HOME:                  /usr/local/cargo
      CC:                          clang
      CXX:                         clang

    steps:

      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.9.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Install dependencies
        run:                       |
          apt-get update
          apt-get install -y --no-install-recommends time clang
          update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100

      - name:                      Install Rust
        run:                       |
          curl -L "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" -o rustup-init
          chmod +x rustup-init
          ./rustup-init -y --no-modify-path --profile minimal --default-toolchain stable
          rm rustup-init
          echo "/usr/local/cargo/bin" >> $GITHUB_PATH
          source /usr/local/cargo/env
          chmod -R a+w ${RUSTUP_HOME} ${CARGO_HOME}
          rustup toolchain install nightly-2021-11-08 --profile minimal --component rustfmt clippy
          ln -s /usr/local/rustup/toolchains/nightly-2021-11-08-x86_64-unknown-linux-gnu /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup show
          cargo --version
          rm -rf "${CARGO_HOME}/registry" "${CARGO_HOME}/git"

      - name:                      Checkout sources
        uses:                      actions/checkout@master

      - name:                      bench-GHA-test-full-crypto-feature
      # GitHub env variables reference: https://docs.github.com/en/actions/learn-github-actions/environment-variables
        run:                       |
          START_TIME=`date '+%s'`
          cd primitives/core/
          time cargo +nightly build --verbose --no-default-features --features full_crypto
          cd ../application-crypto
          time cargo +nightly build --verbose --no-default-features --features full_crypto
          END_TIME=`date '+%s'`
          TOTAL_TIME=`expr $END_TIME - $START_TIME`
          curl -d "parity_github_job_time{project=\"$GITHUB_REPOSITORY\",job=\"$GITHUB_WORKFLOW\",runner=\"github\"} $TOTAL_TIME" -X POST http://vm-longterm.parity-build.parity.io/api/v1/import/prometheus
